name: Update Hash

on:
  push:
    branches:
      - main

jobs:
  update-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Random Hash
        id: generate-hash
        run: echo "::set-output name=hash::$(openssl rand -hex 16)"

      - name: Write Hash in JSON format
        run: |
          echo '{
            "hash": "${{ steps.generate-hash.outputs.hash }}"
          }' > "Blank Grabber/Extras/hash"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update hash"
          git push
